### ISSUE TITLE
sigmoid_backward函数是不是写错了

### ISSUE THREAD

**Issue by tangjicheng1** [yizt/numpy_neural_network#3]
`
def sigmoid_backward(next_dz):

    """

    sigmoid激活反向过程

    :param next_dz:

    :return:

    """

    return sigmoid_forward(1-sigmoid_forward(next_dz))

`

sigmod激活函数的反向传播，应该是

dz = next_dz\*z_{i+1}*z_{i+1}*W_i^{T}

**Comment by yizt** [comment]
@tjich 感谢您的反馈，已修复bug,并增加sigmoid公式推导

**Comment by tangjicheng1** [comment]
OK, Thanks.
